# Generated by Django 4.2.3 on 2024-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_patient', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('weeks_needed', models.CharField(max_length=10)),
                ('service_needed', models.CharField(choices=[('nursing care', 'Nursing care'), ('physiotherapy', 'Physiotherapy')], max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('medical_conditons', models.TextField(max_length=200)),
                ('current_medications', models.TextField(max_length=200)),
            ],
        ),
    ]
